---
title: "Using the R example datasets"
author: "Beverly Ann Boyboy"
date: "2025-09-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###1. Use the R internal CO2 dataset (“data(CO2)”).
```{r}
#load the dataset
data(CO2)

#view summary
summary(CO2)
```

###2. Describe briefly the content of the CO2 dataset using the help function
```{r}
?CO2
```

###3. What is the average and median CO2 uptake of the plants from Quebec and Mississippi?

```{r}
# Separate the CO2 uptake values by plant origin
co2_quebec <- CO2$uptake[CO2$Type == "Quebec"]
co2_mississippi <- CO2$uptake[CO2$Type == "Mississippi"]

# Compute mean and median for each
mean_quebec <- mean(co2_quebec)
median_quebec <- median(co2_quebec)

mean_mississippi <- mean(co2_mississippi)
median_mississippi <- median(co2_mississippi)

mean_quebec
median_quebec
mean_mississippi
median_mississippi
```

###3. [Optional] In the “airway” example data from Bioconductor, how many genes are expressed in each sample? How many genes are not expressed in any sample?

```{r}
#install if not yet done
#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install("airway")

library(airway)
data(airway)
assay_data <- assay(airway)

# Count genes expressed in each sample (expression > 0)
expressed_genes_per_sample <- colSums(assay_data > 0)

# Count genes never expressed in any sample (expression == 0)
never_expressed_genes <- sum(rowSums(assay_data) == 0)

expressed_genes_per_sample
never_expressed_genes
```


